services:

  api:
    build: .
    container_name: healthcare-cost-api

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      # MLflow database
      - ./mlflow.db:/app/mlflow.db

      # MLflow artifact/model storage
      - ./mlruns:/app/mlruns

    environment:
      MLFLOW_TRACKING_URI: sqlite:////app/mlflow.db

    restart: unless-stopped

  frontend:
    build: .
    container_name: healthcare-cost-frontend

    command: >
      streamlit run frontend/streamlit_app.py
      --server.address 0.0.0.0
      --server.port 8501

    ports:
      - "8501:8501"

    environment:
      API_URL: http://api:8000/api/v1/predict

    depends_on:
      - api

    restart: unless-stopped
    